### PR TITLE
Properly detect sponge server implementations

### PR DESCRIPTION
**Pull request by Minecrell**
I'm pretty sure they show up as unknown currently, so that should fix it. :)

### CODE REVIEW

**Comment by Hidendra** [comment]
Thanks! I'll follow up with the changes once there is a new generation.

**Comment by Hidendra** [comment]
Seeing 16 SpongeForge servers now :smile:

**Comment by Hidendra** [comment]
There's still an awfully large number of unknown servers as well. I'll have to take a closer look at those to see what they are.

**Comment by Minecrell** [comment]
Awesome, thank you!

**Comment by Hidendra** [comment]
Just wanted to follow up on this incase you were curious where the unknown servers were coming from.... I finally got the chance to look!

So, data set I was querying: 141215 servers, 17108 unknown server versions detected.

Sample:

| server_software | server_version                              | version_count | 
|-----------------|---------------------------------------------|---------------| 
| Unknown         | 0                                           | 6800          | 
| Unknown         | git-PaperSpigot-1f7d532 (MC: 1.7.10)        | 846           | 
| Unknown         | KCauldron-1.7.10-2.1403.1.54 (MC: 1.7.10)   | 738           | 
| Unknown         | git-PaperSpigot-43 (MC: 1.7.10)             | 700           | 
| Unknown         | git-PaperSpigot-5be55c3-18fbb24 (MC: 1.8.8) | 581           | 
| Unknown         | 1.7.10-1517.168 (MC: 1.7.10)                | 412           | 
| Unknown         | 1.7.10-1481.148 (MC: 1.7.10)                | 386           | 
| Unknown         | 1.7.10-1492.152 (MC: 1.7.10)                | 351           | 
| Unknown         | 1.7.10-1614.175 (MC: 1.7.10)                | 331           | 
| Unknown         | 1.7.10-1448.133 (MC: 1.7.10)                | 285           | 

Picking the easy one, PaperSpigot, **5133 are PaperSpigot**. That's 30% of the unknown servers.

What about server version '0'? That was pretty obvious after looking what plugins they run:

| server_version | plugins_plugin | plugin_count | 
|----------------|----------------|--------------| 
| 0              | 5921           | 6800         | 
| 0              | 12516          | 381          | 
| 0              | 17109          | 137          | 
| ...            |                |              | 

Plugin 5921 is BungeeCord. So they're all BungeeCord! Easily enough to fix.

The rest are a mix of other Spigot/etc impls that can be added or undetectable software.

So, definitions will be updated soon.

**Comment by Hidendra** [comment]
Yep, Unknown servers down to 3% from 12% now :smile:

**Comment by Minecrell** [comment]
Awesome! Unknown server software is now down to 1% from about 30% on ServerListPlus, thank you very much! :)

**Comment by Hidendra** [comment]
The other unknown ones appear to be what looks like KCauldron servers. Unfortunately not so easy to just assign KCauldron :frowning: 

| server_software | server_version               | version_count | 
|-----------------|------------------------------|---------------| 
| Unknown         | 1.7.10-1481.148 (MC: 1.7.10) | 2             | 
| Unknown         | 1.7.10-1517.168 (MC: 1.7.10) | 2             | 
| Unknown         | 1.7.10-1614.174 (MC: 1.7.10) | 2             | 
| Unknown         | 1.7.10-1614.175 (MC: 1.7.10) | 2             | 
| Unknown         | 1.7.10-1448.133 (MC: 1.7.10) | 2             | 
| ...                     |                                                 |               |

**Pull request merged**
