### PR TITLE
Update defintions for Paper(Spigot) 1.9

### PR DESCRIPTION
**Pull request by Zbob750**

### CODE REVIEW

**Comment by Hidendra** [comment]
Is PaperSpigot announcing as `git-Paper-xxx` in 1.9+ now instead of `git-PaperSpigot-xxx`?

**Comment by Zbob750** [comment]
Yes, switched as of 1.9
https://github.com/PaperSpigot/Paper/blob/master/Spigot-Server-Patches/0001-POM-Changes.patch#L68

**Comment by Hidendra** [comment]
Cool. I just imported the latest servers to BigQuery to peek and double confirmed it.

Incase you're curious, here's some of the `XXX` of `git-XXX-...` part of server versions that servers send that have the `PaperSpigot` plugin:

| ProbableSoftware | count | 
|------------------|-------| 
| PaperSpigot      | 4202  | 
| Spigot           | 175   | 
| Paper            | 87    | 
| HexionSpigot     | 25    | 
| R0.1             | 24    | 
| Bukkit           | 18    | 
| ...              |       | 

(although I guess the Server Software graph shows that almost exactly)

**Comment by Hidendra** [comment]
Merged. This'll be reflected in the graph gen in 30 minutes.

**Comment by Zbob750** [comment]
Thanks

**Pull request merged**
